#!/bin/sh
#

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n

start() {
    cd /spec17-intspeed && ./intspeed.sh 641.leela_s --threads 1
    sync
}

case "$1" in
  start)
        start
        ;;
  stop)
        #stop
        ;;
  restart|reload)
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit
